# Site settings
title: Roger Welin
email: roger.welin@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  A tech blog where I will post blog posts about Devops, programming, interesting technologies or just various tips and trix
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rogerwelin.github.io/" # the base hostname & protocol for your site
github_username:  rogerwelin
# Build settings
markdown: kramdown
exclude: [vendor]
gems:
  - jemoji
  - jekyll-sitemap
